# Hyprlock lock screen colors — generated by theme engine
# source'd by config/hypr/hyprlock.conf

$lock_fg = rgb({{ foreground_strip }})
$lock_bg = rgb({{ background_strip }})
$lock_accent = rgb({{ accent_strip }})
$lock_error = rgb({{ color1_strip }})
$lock_muted = rgb({{ color8_strip }})
