# Hyprland border and group colors — generated by theme engine
# source'd by config/hypr/hyprland.conf

general {
    col.active_border = rgba({{ accent_strip }}ee) rgba({{ color5_strip }}ee) 45deg
    col.inactive_border = rgba({{ color8_strip }}aa)
}

group {
    col.border_active = rgba({{ accent_strip }}ee)
    col.border_inactive = rgba({{ color8_strip }}aa)

    groupbar {
        col.active = rgba({{ accent_strip }}ee)
        col.inactive = rgba({{ color8_strip }}aa)
    }
}
