# Mako notification colors — generated by theme engine
# include'd by config/mako/config

background-color={{ background }}
text-color={{ foreground }}
border-color={{ accent }}

[urgency=low]
background-color={{ background }}
text-color={{ color7 }}
border-color={{ color8 }}

[urgency=high]
background-color={{ color1 }}
text-color={{ foreground }}
border-color={{ color1 }}
