# Tofi launcher colors — generated by theme engine
# include'd by config/tofi/config

background-color = {{ background }}
text-color = {{ foreground }}
prompt-color = {{ accent }}
selection-color = {{ accent }}
input-color = {{ cursor }}
default-result-color = {{ color7 }}
border-color = {{ accent }}
outline-color = {{ color0 }}
